name: flutter_riverpod_boilerplate
description: "A comprehensive Flutter boilerplate with Riverpod, Clean Architecture, and modern development practices."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.8.1
  flutter: ">=3.24.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  # State Management & Dependency Injection
  flutter_riverpod: ^2.5.1
  hooks_riverpod: ^2.5.2
  flutter_hooks: ^0.20.5
  riverpod_annotation: ^2.3.5

  # Routing
  go_router: ^13.2.4

  # Code Generation & Serialization
  freezed_annotation: ^2.4.4
  json_annotation: ^4.9.0

  # Backend Services (Optional - configure as needed)
  # supabase_flutter: ^2.5.6
  # firebase_core: ^2.32.0
  # firebase_auth: ^4.20.0
  # firebase_firestore: ^4.17.5

  # Local Storage
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  shared_preferences: ^2.3.3

  # Networking
  dio: ^5.7.0
  pretty_dio_logger: ^1.4.0

  # UI & Theming
  cupertino_icons: ^1.0.8

  # Utilities
  equatable: ^2.0.7
  dartz: ^0.10.1
  intl: ^0.20.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter

  # Linting & Analysis
  flutter_lints: ^5.0.0
  very_good_analysis: ^6.0.0

  # Code Generation
  build_runner: ^2.4.12
  freezed: ^2.5.2
  json_serializable: ^6.8.0
  riverpod_generator: ^2.4.0
  hive_generator: ^2.0.1

  # Testing
  mocktail: ^1.0.4
  fake_async: ^1.3.1

  # Development Tools
  flutter_launcher_icons: ^0.14.1

flutter:
  uses-material-design: true
  generate: true

  assets:
    - assets/images/
    - assets/icons/

  # fonts:
  #   - family: Inter
  #     fonts:
  #       - asset: assets/fonts/Inter-Regular.ttf
  #       - asset: assets/fonts/Inter-Medium.ttf
  #         weight: 500
  #       - asset: assets/fonts/Inter-SemiBold.ttf
  #         weight: 600
  #       - asset: assets/fonts/Inter-Bold.ttf
  #         weight: 700

# Feature Toggles
flutter_riverpod_boilerplate:
  features:
    auto_route: false  # Set to true to use AutoRoute instead of GoRouter
    firebase: false    # Set to true to enable Firebase services
    supabase: true     # Set to true to enable Supabase services
    localization: true # Set to true to enable multi-language support
    dio_logging: true  # Set to true to enable network request logging
